### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by priyavadan** [foxfriends/catan#2]
Hi,

I just tried installing this, got the error below.

ERROR in ./public_html/style/src/main.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/index.js):
Error: ENOENT: no such file or directory, scandir '/var/www/html/catan/node_modules/node-sass/vendor'

**Comment by priyavadan** [comment]
Figured it out, server has started not sure how to start  playing the game though

**Comment by foxfriends** [comment]
Open a game by filling in your name and a game name. Other players can connect to your server and join the same game by putting the same game name. Once 3 or 4 players have connected/chosen a colour the first player can press start and the game will play.
