### ISSUE TITLE
How to interact with game?

### ISSUE THREAD

**Issue by orihomie** [foxfriends/catan#36]
I've tried to launch local game in a dockerfile and also tried to play it on https://catan.cameldridge.com
but no interaction happens when I click somewhere.

I see this error when I launch it in docker:

```
➜  catan git:(main) docker run -p 8888:8888 catan

> catan@0.0.1 start
> babel-node server.js

Server started at 8888
My is attempting to join Try
New game created: Try
[Error: ENOENT: no such file or directory, open './games/Try.game'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './games/Try.game'
}
```

**Comment by foxfriends** [comment]
Ah I will see... I did not test it, only got it running. Maybe more is broken. 

Running in docker may require you to give it a volume at /games/ for it to store the game files in.

**Comment by orihomie** [comment]
If you'd create a file in a mount directory with a name of your game, then it would show you this:

```
> catan@0.0.1 start
> babel-node server.js

Server started at 8888
game is attempting to join my
New game created: my
Game was saved to './games/my.game'
```

So, problem is maybe:
- you don't create file if it's not exists
- you don't have permissions to create that file

**Comment by foxfriends** [comment]
I was able to play the game just fine on catan.cameldridge.com. Maybe you did not add enough players; Catan is a three player game, and I have no AI players.

If all three players join the same named game, then you can click start and play
